# Generated by Django 4.2.7 on 2024-01-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoupounsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('brand', models.CharField(default='', max_length=255)),
                ('discount', models.CharField(default='0', max_length=255)),
                ('min_amount', models.CharField(default='0', max_length=255)),
                ('exp_date', models.CharField(blank=True, default='2024-01-23 09:40:49.521809', max_length=255, null=True)),
                ('desc', models.CharField(default='0', max_length=255)),
            ],
        ),
    ]
